export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const OPEN_FOLDER = "OPEN_FOLDER";
export const CLOSE_FOLDER = "CLOSE_FOLDER";
export const OPEN_NOTICE = "OPEN_NOTICE";
export const OPEN_MYPAGE = "OPEN_MYPAGE";
export const OPEN_RANK = "OPEN_RANK";
export const OPEN_SPONSOR = "OPEN_SPONSOR";
export const OPEN_PWNABLE = "OPEN_PWNABLE";
export const OPEN_REVERSING = "OPEN_REVERSING";
export const OPEN_FORENSIC = "OPEN_FORENSIC";
export const OPEN_WEB = "OPEN_WEB";
export const OPEN_MISC = "OPEN_MISC";

export const OPEN_TERMINAL = "OPEN_TERMINAL";
export const CLOSE_TERMINAL = "CLOSE_TERMINAL";

export const LOAD_PROBLEM_SUCCESS = "LOAD_PROBLEM_SUCCESS";
export const LOAD_PROBLEM_FAIL = "LOAD_PROBLEM_FAIL";

export const SELECT_FOLDER = "SELECT_FOLDER";
export const SELECT_TERMINAL = "SELECT_TERMINAL";
export const SELECT_NOTICE_MODAL = "SELECT_NOTICE_MODAL";

export const OPEN_NOTICE_MODAL = "OPEN_NOTICE_MODAL";
export const CLOSE_NOTICE_MODAL = "CLOSE_NOTICE_MODAL";

export const LOAD_NOTICE_SUCCESS = "LOAD_PROBLEM_SUCCESS";
export const LOAD_NOTICE_FAIL = "LOAD_PROBLEM_FAIL";