export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const OPEN_FOLDER = "OPEN_FOLDER";
export const CLOSE_FOLDER = "CLOSE_FOLDER";
export const OPEN_NOTICE = "OPEN_NOTICE";
export const OPEN_MYPAGE = "OPEN_MYPAGE";
export const OPEN_RANK = "OPEN_RANK";
export const OPEN_SPONSOR = "OPEN_SPONSOR";
export const OPEN_PWNABLE = "OPEN_PWNABLE";
export const OPEN_REVERSING = "OPEN_REVERSING";
export const OPEN_FORENSIC = "OPEN_FORENSIC";
export const OPEN_WEB = "OPEN_WEB";
export const OPEN_MISC = "OPEN_MISC";

export const OPEN_PROBLEM_MODAL = "OPEN_PROBLEM_MODAL";
export const CLOSE_PROBLEM_MODAL = "CLOSE_PROBLEM_MODAL";

export const LOAD_PROBLEM_SUCCESS = "LOAD_PROBLEM_SUCCESS";
export const LOAD_PROBLEM_FAIL = "LOAD_PROBLEM_FAIL";

export const SELECT_FOLDER = "SELECT_FOLDER";
export const SELECT_PROBLEM_MODAL = "SELECT_PROBLEM_MODAL";
export const SELECT_NOTICE_MODAL = "SELECT_NOTICE_MODAL";
export const DESELECT_FOLDER = "DESELECT_FOLDER";
export const DESELECT_PROBLEM_MODAL = "DESELECT_PROBLEM_MODAL";
export const DESELECT_NOTICE_MODAL = "DESELECT_NOTICE_MODAL";

export const OPEN_NOTICE_MODAL = "OPEN_NOTICE_MODAL";
export const CLOSE_NOTICE_MODAL = "CLOSE_NOTICE_MODAL";

export const LOAD_NOTICE_SUCCESS = "LOAD_PROBLEM_SUCCESS";
export const LOAD_NOTICE_FAIL = "LOAD_PROBLEM_FAIL";

export const LOAD_MYPAGE_SUCCESS = "LOAD_MYPAGE_SUCCESS";
export const LOAD_MYPAGE_FAIL = "LOAD_MYPAGE_FAIL";

export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
export const OPEN_NOTIFICATION = "OPEN_NOTIFICATION";

export const LOAD_NOTIFICATION_SUCCESS = "LOAD_NOTIFICATION_SUCCESS";
export const LOAD_NOTIFICATION_FAIL = "LOAD_NOTIFICATION_FAIL";

export const REMOVE_NOTIFICATION_SUCCESS = "REMOVE_NOTIFICATION_SUCCESS";
export const REMOVE_NOTIFICATION_FAIL = "REMOVE_NOTIFICATION_FAIL";

export const READ_NOTIFICATIONS = "READ_NOTIFICATIONS";